# Generated by Django 3.0.2 on 2020-03-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200314_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='activate',
            new_name='active',
        ),
    ]
