# Generated by Django 3.0.2 on 2020-02-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200204_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='activate',
            new_name='active',
        ),
    ]
